### PR TITLE
:sparkles: disable button when clicked

### LINKED ISSUE #7: Make a choice unclickable after the first try if this is a wrong choice
So the user won't loose n times by clicking on the wrong choice

### PR DESCRIPTION
**Pull request by delphinemillet**
fixes #7

### CODE REVIEW

File: src/store/choice/choice.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { types } from 'mobx-state-tree'
+
+/* eslint-disable no-param-reassign */
+
+export default types
+  .model({
+    selected: types.boolean,
```
Comment (fabienjuif) [inline src/store/choice/choice.js]: `selected: false`

File: src/store/choice/index.js [hunk 2]
```diff
@@ -0,0 +1 @@
+export { default } from './choice'
```
Comment (fabienjuif) [inline src/store/choice/index.js]: Move `choice` directory into `draw` one since only `Draw` model use it

File: src/store/draw/draw.js [hunk 3]
```diff
@@ -16,3 +17,14 @@ export default types
       self.choices = shuffle(self.choices.peek())
     },
   }))
+  .preProcessSnapshot(({
```
Comment (fabienjuif) [inline src/store/draw/draw.js]:
```es6
.preProcessSnapshot(({ choices, ...rest }) => ({
  ...rest,
  choices: choices.map(choice => ({ url: choice })),
}
```

**Review by fabienjuif — CHANGES_REQUESTED** [review]
some comments

**Review by fabienjuif — APPROVED** [review]
👍 👍
